[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/api/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
